name: Model-Sales-Prediction
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all 
    steps:
    - uses: actions/checkout@v3
    - uses: iterative/setup-cml@v1
    - name: train_model
      env:
         repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # your ML workflow goes here
        pip install -r requirements.txt
        python train/RandomForest.py
        
    - name: 'Write CML report'
      env:
         REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Post reports as comments in GitHub PRs
        # Random Regression
        echo "Model Metrics" >> report.md
        cat train/metrics.txt >> report.md
        echo "Data Visualization" >> report.md
        echo "Predicted vs. actual accuracy" >> report.md
        echo "Feature Importance" >> report.md
        cml-publish images/featureImportance.png --md >> report.md
          
        cml-send-comment report.md
        
